### ISSUE TITLE
Rv bugfixes

### ISSUE THREAD

**Issue by joshspeagle** [joshspeagle/brutus#16]
Small bugs (thanks @catherinezucker) that are around after the Rv variation commit:
- [x] binning pdfs for distance-reddening plots has bugs
- [x] SED generation is currently broken with respect to Rv and making grids

**Comment by catherinezucker** [comment]
In the bin_pdfs_distred function, it says it accepts a "coord" object in the documentation, but it actually accepts a variable named "coords." Also it says it's optional but if you don't provide it, it breaks.

**Comment by catherinezucker** [comment]
Also, Rv is no longer accepted as input argument, but it is found on line 768 so it breaks by default
