### ISSUE TITLE
Update versions

### ISSUE THREAD

**Issue by gusbeane** [joshspeagle/brutus#36]
It does not appear that `v0.8.0` or `v0.8.1` are released as versions

**Comment by joshspeagle** [comment]
Yes, these were mostly for internal tracking (I'm sloppy with use of version numbers). I plan to cut some of these to Zenodo and release them as versions once I can confirm they are stable.

**Comment by gusbeane** [comment]
A new version `v0.8.2` has been added as a draft, @joshspeagle can you check/edit and submit it and close this issue when you are happy?

This is the current pip version

**Comment by joshspeagle** [comment]
This is now live.
