### ISSUE TITLE
Fix numpy arrays being modified out of scope

### ISSUE THREAD

**Issue by gusbeane** [joshspeagle/brutus#40]
Found in _optimize_fit, where the input av will be modified outside of scope. Does not affect results at the moment, but should be cleaned up at some point to prevent future errors. (And should be found in other parts of code.)

**Comment by joshspeagle** [comment]
This technically is accessible to the users but only through functions tagged as internal, but I agree I should probably make things a bit safer here.

**Comment by joshspeagle** [comment]
With the refactoring of these functions, I don't think this is actually as much of a concern for the immediate time being. I'm going to close this for now. We can reopen it if it becomes a problem again.
