### ISSUE TITLE
wt_thresh duplicate

### ISSUE THREAD

**Issue by gusbeane** [joshspeagle/brutus#41]
There shouldn't be two `wt_thresh` variables running around.

**Comment by gusbeane** [comment]
`wt_thresh`*

**Comment by joshspeagle** [comment]
Yes, I should redefine the internals of `loglike` and any other associated functions to actually track the variable names used in `fit`. Thanks.

**Comment by gusbeane** [comment]
In `fit`, the parameter `log_initthresh` is passed to `_optimize_fit` as `init_thresh`, and within `_optimize_fit` the action `log(init_thresh)` is taken, so this breaks a user-facing parameter, since one would often want to set `log_initthresh < 0`. Adding a bug label

**Comment by joshspeagle** [comment]
Note that it is technically `logl`, not `log`. So this isn't actually a bug.
