### ISSUE TITLE
Make brutus pip installable

### ISSUE THREAD

**Issue by gusbeane** [joshspeagle/brutus#42]
I can look into this as it's something I'd like to learn about

**Comment by catherinezucker** [comment]
I already know how to do this! I did it for my RadFil package. I can send
you some links.

**Comment by joshspeagle** [comment]
Yes, it's quite straightforward, so happy to leave this to you. I would wait until after the next version update to `0.8.X` before trying anything though.

**Comment by gusbeane** [comment]
I can just make v0.7.5 and 0.7.0 installable for now, since only official releases should be available through pip anyways

Links would be great Catherine!

**Comment by catherinezucker** [comment]
This is what I used two years ago...hopefully it's not too outdated. Give it a try, maybe?

https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56

**Comment by gusbeane** [comment]
Ok looks like some small changes need to be made to `setup.py`, so will just do this for `0.8.x` as @joshspeagle suggested, rather than retrofitting `0.7.x` releases

**Comment by gusbeane** [comment]
Done, can now be installed with `pip install astro-brutus`
