### ISSUE TITLE
Include instructions on how to run brutus

### ISSUE THREAD

**Issue by davehouser1** [joshspeagle/brutus#48]
I tried pip installing, as well as installing via the setup.py script, but its not clear how to run brutus. I see nothing in my path either. Where is brutus installed? How do I run it? 
Maybe some examples on how to run it as well would be helpful.

**Comment by joshspeagle** [comment]
Examples of usage can be found under [`demos`](https://github.com/joshspeagle/brutus/tree/master/demos) in the notebooks labelled from 0-6. The install location is the same as other packages installed via `pip` under the name `astro-brutus`.

As this is a repeat of a previous issue (this is currently on the to-do list under #29), I'll close this one for now. I can re-open it if you have a particular issue that you don't think is addressed in the notebooks.
